volumes:
  dev-db-volume: {}
services:
  dev-pg12:
    container_name: dbpg4
    hostname: lala4
    image: bitnami/postgresql:17.2.0
    environment:
      POSTGRESQL_DATABASE: cursa4
      POSTGRESQL_USERNAME: eoeqs
      POSTGRESQL_PASSWORD: eoeqs
    volumes:
      - dev-db-volume:/bitnami/postgresql
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eoeqs"]
      interval: 5s
      timeout: 5s
      retries: 3
